apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres
        env:
          - name: POSTGRES_PASSWORD
            value: password
        ports:
        - containerPort: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
  - port: 5432
    protocol: TCP
  selector:
    app: postgres

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: mozilla/tls-observatory
        imagePullPolicy: IfNotPresent
        command:
          - /app/tlsobs-api
        env:
          - name: TLSOBS_POSTGRES
            value: postgres
          - name: TLSOBS_POSTGRESUSER
            value: tlsobsapi
          - name: TLSOBS_POSTGRESPASS
            value: mysecretpassphrase
        ports:
        - containerPort: 8083

---

apiVersion: v1
kind: Service
metadata:
  name: api
spec:
  type: NodePort
  ports:
  - port: 8083
    protocol: TCP
  selector:
    app: api

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: scanner
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: scanner
    spec:
      containers:
      - name: scanner
        image: mozilla/tls-observatory
        imagePullPolicy: IfNotPresent
        command:
          - /app/tlsobs-scanner
        env:
          - name: TLSOBS_POSTGRES
            value: postgres
          - name: TLSOBS_POSTGRESUSER
            value: tlsobsscanner
          - name: TLSOBS_POSTGRESPASS
            value: mysecretpassphrase
